### ISSUE TITLE
Would be great if: kurt could tell me which CONTAINER crashed in a multi-container POD

### ISSUE THREAD

**Issue by alan-copeland-keysight** [soraro/kurt#40]
**Is your feature request related to a problem? Please describe.**

I have a multi-container pod, i.e. it has 3 containers, which communicate with each other to do various things on localhost. Its in active development by multiple teams so the crash could possibly be in any of the 3 containers. It would be great if kurt were able to tell me which container was causing the pod restart?

**Comment by alan-copeland-keysight** [comment]
The way I've been debugging this today (across the multiple containers):
1. change container command to "sleep 3600"
2. exec into the pod
3. run the command manually
4. see if the container keeps running, or if its the one that crashes

Doing this across multiple pods allows me to see which container errors out, and which containers continue, but its kind of annoying :)

**Comment by alan-copeland-keysight** [comment]
Is this a good usecase for kurt, or any other suggestions?

**Comment by kwsorensen** [comment]
I think this could be a good use case for kurt,  if the information is stored.  Let me do some initial investigation and I'll get back with more info.

**Comment by aro5000** [comment]
@alan-copeland-keysight thanks for raising this! We do indeed get all of the container restart counts when we iterate through pods given the parameters provided. Currently we just add these together to get the pod count, but it's certainly available to us at a container level as well. How would you expect this command to look?
```
kurt containers
```
Would that output all containers across all pods in the given namespace constraints?

Would you expect it to be more like this so it targets only one pod?
```
kurt container <pod-name>
```

The challenge I see is how the output would look, or how it would be grouped (if at all, since container names do not need to be unique unlike pod names within a namespace)

A sample output or command would be helpful if we move forward with this 🙂

**Comment by aro5000** [comment]
Or maybe a flag like:
```
kurt pods --include-containers
```

**Comment by alan-copeland-keysight** [comment]
I sort of like your last one with a flag:

```kurt pods --show-containers```

Or maybe if you want to filter to a specific pod

```kurt pods <pod-name> --show-containers```

It would probably also be useful for DaemonSets/Deployments/StatefulSets as well, but if you just started with Pods that would solve the primary need!

**Comment by aro5000** [comment]
@alan-copeland-keysight I have a PR up at #41 if you want to / are willing to try out this new functionality! @kwsorensen and I are still going back and forth on the best way to actually display this data in the "standard" output, but we would appreciate any input you have, and whether this behaves as you'd expect.
